export type BattleCategory = 'MISS' | 'DODGE' | 'LIGHT_HIT' | 'MEDIUM_HIT' | 'HEAVY_HIT' | 'CRITICAL_HIT' | 'FINISHER';

export const MMA_MOVES = [
  'jab',
  'cross',
  'hook',
  'uppercut',
  'body kick',
  'leg kick',
  'spinning backfist',
  'knee strike',
  'elbow strike',
  'takedown',
  'submission attempt',
  'power punch',
  'spinning heel kick',
  'teep kick',
  'overhand right',
  'roundhouse kick',
];

export const BATTLE_DATA: Record<BattleCategory, string[]> = {
  MISS: [
    '{attacker}\'s {move} sails high over {defender}\'s head.',
    'No connection! {attacker} whiffs the {move} completely.',
    '{defender} was never in danger. The {move} misses cleanly.',
    '{attacker} commits to the {move}, but {defender} isn\'t there.',
    'Timing is off. {attacker}\'s {move} fails to land.',
    '{attacker}\'s {move} comes up short by a full distance.',
    'The canvas gets hit instead of {defender}.',
    '{attacker} overshoots with the {move}.',
    'Wide! {attacker}\'s {move} doesn\'t find its mark.',
    'A telegraphed {move} from {attacker} finds nothing but air.',
    '{defender} reads the {move} and steps aside.',
    '{attacker}\'s {move} is well-dodged by {defender}.',
    'No effect. The {move} is completely evasible.',
    '{attacker} throws the {move} with insufficient range.',
    'The {move} passes {defender} by inches.',
    '{attacker}\'s attempt at a {move} comes up short.',
    'Well-timed footwork from {defender} avoids the {move}.',
    'The {move} doesn\'t connect. {defender} is untouched.',
    '{attacker} overcommits on the {move}.',
    'Ineffective range management on that {move}.',
    '{defender} is never threatened by that {move}.',
    'The {move} from {attacker} is poorly placed.',
    'No dice. {attacker}\'s {move} completely misses.',
    '{attacker} swings and misses with the {move}.',
    'Completely avoided by {defender}!',
    'The {move} might as well not have happened.',
    '{defender}\'s positioning defeats the {move}.',
    '{attacker} needs better timing on that {move}.',
    'Even the referee yawns at that missed {move}.',
    'That {move} from {attacker} registers zero impact.',
  ],
  DODGE: [
    '{defender} slips the {move} with exceptional footwork!',
    'Brilliant head movement from {defender}!',
    '{attacker}\'s {move} is narrowly avoided.',
    '{defender} ducks under the incoming {move}.',
    'Excellent evasion! {defender} reads {attacker}\'s {move}.',
    '{defender} rolls and weaves past the {move}.',
    '{attacker} commits but {defender} is moving.',
    'Quick lateral movement from {defender} avoids the {move}.',
    '{defender} displays defensive awareness, dodging the {move}.',
    'That {move} whistles past {defender}\'s ear!',
    '{defender} slips inside and avoids the {move}.',
    'Explosive footwork from {defender}!',
    '{defender} parries and slips the {move}.',
    '{attacker}\'s {move} is defeated by {defender}\'s movement.',
    '{defender} anticipates the {move} perfectly.',
    'Pure striking defense from {defender}!',
    '{defender} slides back from the {move}.',
    'Masterful evasion! The {move} is dodged.',
    '{defender} uses distance management perfectly.',
    '{attacker}\'s {move} is read like a book.',
    'Picture-perfect head movement from {defender}!',
    '{defender}\'s ring awareness prevents the {move}.',
    'The {move} finds no target.',
    '{defender} makes {attacker} miss look foolish.',
    'Defensive masterclass from {defender}!',
    'That {move} was telegraph city!',
    '{defender} responds with flawless positioning.',
    'The {move} cannot land against such defense.',
    '{defender} shifts angle and evades.',
    'Textbook evasion from {defender}!',
  ],
  LIGHT_HIT: [
    '{attacker}\'s {move} clips {defender} lightly on the arm.',
    'Light contact from {attacker}\'s {move}.',
    '{attacker}\'s {move} connects, but {defender} absorbs it.',
    'A glancing {move} from {attacker} reaches {defender}.',
    '{defender} feels minimal damage from the {move}.',
    '{attacker}\'s {move} finds the mark lightly.',
    'Partial connection on {attacker}\'s {move}.',
    '{defender} takes a light shot from {attacker}\'s {move}.',
    'Minimal damage from {attacker}\'s {move}.',
    '{attacker}\'s {move} lands but lacks power.',
    'Grazing contact from that {move}.',
    '{defender} shrugs off the light {move}.',
    'Not significant damage from {attacker}\'s {move}.',
    '{attacker} connects with a light {move}.',
    'Minor damage dealt by {attacker}\'s {move}.',
    'The {move} finds {defender}, barely.',
    '{defender} is minimally affected.',
    '{attacker}\'s positioning registers contact.',
    'A soft {move} from {attacker} makes contact.',
    'Superficial damage from {attacker}\'s {move}.',
    '{attacker}\'s {move} scores a minor point.',
    '{defender} absorbs the light {move}.',
    'Inefficient striking from {attacker}.',
    'A tentative {move} from {attacker}.',
    '{defender} takes the light strike and drives forward.',
    'Soft but controlled contact from {attacker}.',
    '{defender} is bothered but not hurt.',
    '{attacker} lands light on {defender}.',
    'Scoring contact without power.',
    'That {move} registers on the judges\' cards only.',
  ],
  MEDIUM_HIT: [
    '{attacker} connects with a solid {move} on {defender}!',
    'Good contact! {attacker}\'s {move} lands clean.',
    '{defender} feels that {move} from {attacker}!',
    '{attacker}\'s {move} snaps {defender}\'s head back slightly.',
    'Effective striking! The {move} lands squarely on {defender}.',
    '{attacker} times the {move} perfectly.',
    'That {move} has {defender}\'s full attention!',
    '{defender} takes a solid {move} to the body.',
    '{attacker}\'s {move} creates separation.',
    'Clean striking from {attacker}! The {move} connects beautifully.',
    '{attacker} lands the {move} with authority.',
    'Significant damage dealt by {attacker}\'s {move}!',
    '{defender} staggers slightly from the {move}.',
    '{attacker}\'s {move} is perfectly executed.',
    'Real power behind that {move} from {attacker}!',
    '{defender} is rocked by {attacker}\'s {move}!',
    'The {move} from {attacker} has serious impact!',
    '{defender} grimaces from the {move}.',
    '{attacker} lands a tactical {move} on {defender}.',
    'Impressive technique on that {move}!',
    '{attacker}\'s {move} is textbook execution.',
    '{defender} absorbs a substantial {move}.',
    'Quality striking displayed by {attacker}!',
    '{attacker} times and distances perfectly.',
    'Visible impact from that {move}!',
    'That {move} will accumulate significant damage!',
    '{defender} nods—they felt that {move}.',
    'Professional striking from {attacker}!',
    'The {move} registers clearly on {defender}.',
    'Textbook form on that {move}!',
  ],
  HEAVY_HIT: [
    'A DEVASTATING {move} from {attacker} rocks {defender}!',
    '{defender} is badly hurt! {attacker}\'s {move} lands with serious force!',
    'TREMENDOUS IMPACT! {attacker}\'s {move} staggers {defender}!',
    '{defender} is visibly shaken by the {move}!',
    'That {move} from {attacker} is POWERFUL!',
    '{attacker} unloads the {move} with full force on {defender}!',
    'The {move} from {attacker} is absolutely BRUTAL!',
    '{defender} buckles under the force of the {move}!',
    'MAJOR DAMAGE! {attacker}\'s {move} is a SHOT!',
    '{attacker} connects with a THUNDEROUS {move}!',
    'The {move} lands WITH AUTHORITY!',
    '{defender} is rocked hard by the {move}!',
    'A DESTRUCTIVE {move} from {attacker} lands square!',
    '{attacker}\'s {move} has {defender} in trouble!',
    'SIGNIFICANT DAMAGE DEALT! The {move} from {attacker} is VIOLENT!',
    '{defender} is clearly affected—that {move} was HARD!',
    'The {move} from {attacker} carries TREMENDOUS FORCE!',
    '{defender} is shaken up! The {move} was SUBSTANTIAL!',
    'PUNISHING {move} from {attacker}!',
    '{attacker} lands a CRUSHING {move}!',
    'The impact of the {move} is EVIDENT on {defender}!',
    '{attacker}\'s {move} is PRECISION STRIKING WITH POWER!',
    '{defender} is hurt badly by that {move}!',
    'A POWERFUL element in that {move}!',
    'The {move} from {attacker} is DAMAGING!',
    '{defender} is staggered significantly!',
    'SERIOUS DAMAGE! That {move} from {attacker} was VICIOUS!',
    'The {move} lands with POWER!',
    '{attacker}\'s {move} is a STATEMENT!',
    'The {move} from {attacker} breaks {defender}\'s rhythm!',
  ],
  CRITICAL_HIT: [
    'THAT IS A DEVASTATING BLOW! {attacker}\'s {move} catches {defender} FLUSH!',
    '{defender} IS IN SERIOUS TROUBLE! The {move} from {attacker} is PRECISION!',
    'CRITICAL DAMAGE! A {move} of TREMENDOUS POWER!',
    'THE {move} FROM {attacker} IS ABSOLUTELY LETHAL!',
    '{defender} IS HURT BADLY! {attacker}\'s {move} is CATASTROPHIC!',
    'THE REFEREE MAY NEED TO STEP IN! {attacker}\'s {move} is DEVASTATING!',
    'THAT\'S A POTENTIAL FINISHING BLOW! The {move} from {attacker}!',
    '{defender} IS COMPROMISED AFTER THAT {move}!',
    'CRITICAL CONDITION! {attacker}\'s {move} lands FLUSH!',
    'THE {move} IS A SHOW OF SUPERIOR TECHNIQUE!',
    'SPECTACULAR FINISH INCOMING? {attacker}\'s {move}!',
    'THE {move} FROM {attacker} IS CHAMPIONSHIP-LEVEL STRIKING!',
    '{defender} seems to be FADING from {attacker}\'s {move}!',
    'IS THIS THE TURNING POINT? {attacker}\'s {move}!',
    'THAT {move} FROM {attacker} COULD DECIDE THIS FIGHT!',
    'THE PRECISION! THE POWER! {attacker}\'s {move} lands PERFECTLY!',
    '{defender} IS ON THE BRINK! The {move} was DEVASTATING!',
    'THE {move} FROM {attacker} IS A STATEMENT!',
    'CRITICAL HIT! {attacker}\'s {move} lands WITH AUTHORITY!',
    'THE FIGHT COULD BE OVER! {attacker}\'s {move} is OVERWHELMING!',
    'THAT IS A CHAMPIONSHIP {move} FROM {attacker}!',
    '{defender} IS SEVERELY HURT! THE {move} WAS MERCILESS!',
    'THE {move} FROM {attacker} IS AN EXECUTION!',
    'WILL {defender} SURVIVE THIS? {attacker}\'s {move} is FATAL!',
    'THE {move} FROM {attacker} IS MATCH-CHANGING!',
    'THE REFEREE IS WATCHING CLOSELY! {attacker}\'s {move}!',
    'THAT {move} FROM {attacker} COULD CHANGE EVERYTHING!',
    'THE {move} IS A TECHNICAL MASTERPIECE!',
    'CRITICAL DAMAGE! {attacker} HAS {defender} ON THE BRINK!',
    'THIS IS IT! {attacker}\'s {move} MIGHT BE THE END!',
  ],
  FINISHER: [
    '{attacker} DELIVERS A FINISHING {move}! {defender} IS DOWN!',
    'KNOCKOUT! {attacker}\'s {move} IS ABSOLUTELY DEVASTATING!',
    'IT\'S OVER! THE {move} FROM {attacker} ENDS THIS!',
    '{defender} IS FINISHED! THE {move} FROM {attacker} IS FINAL!',
    'THE {move} FROM {attacker}—THAT IS A KNOCKOUT!',
    'LIGHTS OUT! {attacker}\'s {move} HAS DONE IT!',
    'THE REFEREE STEPS IN! {attacker}\'s {move} HAS ENDED THIS FIGHT!',
    '{defender} IS OUT! {attacker} WINS WITH A BRUTAL {move}!',
    'MATCH OVER! THE {move} FROM {attacker} IS FINAL!',
    'SUBMISSION INCOMING! {attacker}\'s {move} HAS FORCED THE ISSUE!',
    '{attacker} SECURES VICTORY! THE {move} WAS IMMACULATE!',
    'THIS IS CHAMPIONSHIP-LEVEL FINISHING TECHNIQUE!',
    'THE {move} FROM {attacker} IS AN INSTANT CLASSIC!',
    'FIGHT ENDS NOW! {defender} CANNOT CONTINUE!',
    'THE {move}—A MASTERCLASS IN KNOCKOUT POWER!',
    '{attacker} DOMINATED THE FINISH! THE {move} IS PERFECT!',
    '{defender} HAS NO ANSWER! THE {move} FROM {attacker}!',
    'THE WINNING {move} FROM {attacker}!',
    '{attacker} SHOWS SUPREME STRIKING! THE {move} ENDS ALL DEBATE!',
    'THIS IS A STATEMENT VICTORY! THE {move} FROM {attacker}!',
    'THE FINISHING SEQUENCE FROM {attacker} IS PERFECTION!',
    '{defender} IS NO LONGER ABLE TO DEFEND! {attacker} WINS!',
    'THAT IS ELITE-LEVEL COMBAT TECHNIQUE!',
    'THE {move} FROM {attacker} WILL BE REPLAYED FOR YEARS!',
    '{attacker} IS THE VICTOR! AN OUTSTANDING FINISH!',
    'THE SKILL, THE TIMING, THE POWER—{attacker} SHOWS IT ALL!',
    'A COMPLETE AND DOMINANT VICTORY FOR {attacker}!',
    'THE {move} ENDS THIS CONTEST DECISIVELY!',
    'WHAT A FINISH! {attacker} IS TRIUMPHANT!',
    '{defender} IS DEFEATED! {attacker} STANDS VICTORIOUS!',
  ],
};

/**
 * Get a random phrase from a category
 */
export const getRandomPhrase = (category: BattleCategory): string => {
  const phrases = BATTLE_DATA[category];
  return phrases[Math.floor(Math.random() * phrases.length)];
};

/**
 * Replace placeholders in a phrase with actual values
 */
export const formatPhrase = (
  phrase: string,
  attacker: string,
  defender: string,
  move: string
): string => {
  return phrase
    .replace(/{attacker}/g, attacker)
    .replace(/{defender}/g, defender)
    .replace(/{move}/g, move);
};

/**
 * Get a formatted battle message
 */
export const getBattleMessage = (
  category: BattleCategory,
  attacker: string,
  defender: string,
  move: string
): string => {
  const phrase = getRandomPhrase(category);
  return formatPhrase(phrase, attacker, defender, move);
};
