import { Language } from '../context/LanguageContext';

export type BattleCategory = 'MISS' | 'DODGE' | 'LIGHT_HIT' | 'MEDIUM_HIT' | 'HEAVY_HIT' | 'CRITICAL_HIT' | 'FINISHER';

// MMA Moves in all languages
export const MMA_MOVES: Record<Language, string[]> = {
  en: [
    'jab', 'cross', 'hook', 'uppercut', 'body kick', 'leg kick',
    'spinning backfist', 'knee strike', 'elbow strike', 'takedown',
    'submission attempt', 'power punch', 'spinning heel kick', 'teep kick',
    'overhand right', 'roundhouse kick',
  ],
  cs: [
    'přímý úder', 'křížový úder', 'hák', 'uppercut', 'kop na tělo', 'low kick',
    'otočný backfist', 'kop kolenem', 'úder loktem', 'takedown',
    'pokus o submisi', 'silový úder', 'otočný kop', 'teep kick',
    'overhand pravačka', 'kruhový kop',
  ],
  pl: [
    'prosty cios', 'krzyżowy cios', 'sierpowy', 'uppercut', 'kopnięcie w korpus', 'low kick',
    'obrotowy cios z tyłu', 'kopnięcie kolanem', 'cios łokciem', 'powale nie',
    'próba poddania', 'mocny cios', 'obrotowe kopnięcie', 'kopnięcie czołowe',
    'overhand prawą', 'kopnięcie okrężne',
  ],
};

// Battle phrases in all languages
export const BATTLE_DATA: Record<Language, Record<BattleCategory, string[]>> = {
  en: {
    MISS: [
      '{attacker}\'s {move} sails high over {defender}\'s head.',
      'No connection! {attacker} whiffs the {move} completely.',
      '{defender} was never in danger. The {move} misses cleanly.',
      '{attacker} commits to the {move}, but {defender} isn\'t there.',
      'Timing is off. {attacker}\'s {move} fails to land.',
      '{attacker}\'s {move} comes up short by a full distance.',
      'The canvas gets hit instead of {defender}.',
      '{attacker} overshoots with the {move}.',
      'Wide! {attacker}\'s {move} doesn\'t find its mark.',
      'A telegraphed {move} from {attacker} finds nothing but air.',
      '{defender} reads the {move} and steps aside.',
      '{attacker}\'s {move} is well-dodged by {defender}.',
      'No effect. The {move} is completely evasible.',
      '{attacker} throws the {move} with insufficient range.',
      'The {move} passes {defender} by inches.',
      '{attacker}\'s attempt at a {move} comes up short.',
      'Well-timed footwork from {defender} avoids the {move}.',
      'The {move} doesn\'t connect. {defender} is untouched.',
      '{attacker} overcommits on the {move}.',
      'Ineffective range management on that {move}.',
      '{defender} is never threatened by that {move}.',
      'The {move} from {attacker} is poorly placed.',
      'No dice. {attacker}\'s {move} completely misses.',
      '{attacker} swings and misses with the {move}.',
      'Completely avoided by {defender}!',
      'The {move} might as well not have happened.',
      '{defender}\'s positioning defeats the {move}.',
      '{attacker} needs better timing on that {move}.',
      'Even the referee yawns at that missed {move}.',
      'That {move} from {attacker} registers zero impact.',
    ],
    DODGE: [
      '{defender} slips the {move} with exceptional footwork!',
      'Brilliant head movement from {defender}!',
      '{attacker}\'s {move} is narrowly avoided.',
      '{defender} ducks under the incoming {move}.',
      'Excellent evasion! {defender} reads {attacker}\'s {move}.',
      '{defender} rolls and weaves past the {move}.',
      '{attacker} commits but {defender} is moving.',
      'Quick lateral movement from {defender} avoids the {move}.',
      '{defender} displays defensive awareness, dodging the {move}.',
      'That {move} whistles past {defender}\'s ear!',
      '{defender} slips inside and avoids the {move}.',
      'Explosive footwork from {defender}!',
      '{defender} parries and slips the {move}.',
      '{attacker}\'s {move} is defeated by {defender}\'s movement.',
      '{defender} anticipates the {move} perfectly.',
      'Pure striking defense from {defender}!',
      '{defender} slides back from the {move}.',
      'Masterful evasion! The {move} is dodged.',
      '{defender} uses distance management perfectly.',
      '{attacker}\'s {move} is read like a book.',
      'Picture-perfect head movement from {defender}!',
      '{defender}\'s ring awareness prevents the {move}.',
      'The {move} finds no target.',
      '{defender} makes {attacker} miss look foolish.',
      'Defensive masterclass from {defender}!',
      'That {move} was telegraph city!',
      '{defender} responds with flawless positioning.',
      'The {move} cannot land against such defense.',
      '{defender} shifts angle and evades.',
      'Textbook evasion from {defender}!',
    ],
    LIGHT_HIT: [
      '{attacker}\'s {move} clips {defender} lightly on the arm.',
      'Light contact from {attacker}\'s {move}.',
      '{attacker}\'s {move} connects, but {defender} absorbs it.',
      'A glancing {move} from {attacker} reaches {defender}.',
      '{defender} feels minimal damage from the {move}.',
      '{attacker}\'s {move} finds the mark lightly.',
      'Partial connection on {attacker}\'s {move}.',
      '{defender} takes a light shot from {attacker}\'s {move}.',
      'Minimal damage from {attacker}\'s {move}.',
      '{attacker}\'s {move} lands but lacks power.',
      'Grazing contact from that {move}.',
      '{defender} shrugs off the light {move}.',
      'Not significant damage from {attacker}\'s {move}.',
      '{attacker} connects with a light {move}.',
      'Minor damage dealt by {attacker}\'s {move}.',
      'The {move} finds {defender}, barely.',
      '{defender} is minimally affected.',
      '{attacker}\'s positioning registers contact.',
      'A soft {move} from {attacker} makes contact.',
      'Superficial damage from {attacker}\'s {move}.',
      '{attacker}\'s {move} scores a minor point.',
      '{defender} absorbs the light {move}.',
      'Inefficient striking from {attacker}.',
      'A tentative {move} from {attacker}.',
      '{defender} takes the light strike and drives forward.',
      'Soft but controlled contact from {attacker}.',
      '{defender} is bothered but not hurt.',
      '{attacker} lands light on {defender}.',
      'Scoring contact without power.',
      'That {move} registers on the judges\' cards only.',
    ],
    MEDIUM_HIT: [
      '{attacker} connects with a solid {move} on {defender}!',
      'Good contact! {attacker}\'s {move} lands clean.',
      '{defender} feels that {move} from {attacker}!',
      '{attacker}\'s {move} snaps {defender}\'s head back slightly.',
      'Effective striking! The {move} lands squarely on {defender}.',
      '{attacker} times the {move} perfectly.',
      'That {move} has {defender}\'s full attention!',
      '{defender} takes a solid {move} to the body.',
      '{attacker}\'s {move} creates separation.',
      'Clean striking from {attacker}! The {move} connects beautifully.',
      '{attacker} lands the {move} with authority.',
      'Significant damage dealt by {attacker}\'s {move}!',
      '{defender} staggers slightly from the {move}.',
      '{attacker}\'s {move} is perfectly executed.',
      'Real power behind that {move} from {attacker}!',
      '{defender} is rocked by {attacker}\'s {move}!',
      'The {move} from {attacker} has serious impact!',
      '{defender} grimaces from the {move}.',
      '{attacker} lands a tactical {move} on {defender}.',
      'Impressive technique on that {move}!',
      '{attacker}\'s {move} is textbook execution.',
      '{defender} absorbs a substantial {move}.',
      'Quality striking displayed by {attacker}!',
      '{attacker} times and distances perfectly.',
      'Visible impact from that {move}!',
      'That {move} will accumulate significant damage!',
      '{defender} nods—they felt that {move}.',
      'Professional striking from {attacker}!',
      'The {move} registers clearly on {defender}.',
      'Textbook form on that {move}!',
    ],
    HEAVY_HIT: [
      'A DEVASTATING {move} from {attacker} rocks {defender}!',
      '{defender} is badly hurt! {attacker}\'s {move} lands with serious force!',
      'TREMENDOUS IMPACT! {attacker}\'s {move} staggers {defender}!',
      '{defender} is visibly shaken by the {move}!',
      'That {move} from {attacker} is POWERFUL!',
      '{attacker} unloads the {move} with full force on {defender}!',
      'The {move} from {attacker} is absolutely BRUTAL!',
      '{defender} buckles under the force of the {move}!',
      'MAJOR DAMAGE! {attacker}\'s {move} is a SHOT!',
      '{attacker} connects with a THUNDEROUS {move}!',
      'The {move} lands WITH AUTHORITY!',
      '{defender} is rocked hard by the {move}!',
      'A DESTRUCTIVE {move} from {attacker} lands square!',
      '{attacker}\'s {move} has {defender} in trouble!',
      'SIGNIFICANT DAMAGE DEALT! The {move} from {attacker} is VIOLENT!',
      '{defender} is clearly affected—that {move} was HARD!',
      'The {move} from {attacker} carries TREMENDOUS FORCE!',
      '{defender} is shaken up! The {move} was SUBSTANTIAL!',
      'PUNISHING {move} from {attacker}!',
      '{attacker} lands a CRUSHING {move}!',
      'The impact of the {move} is EVIDENT on {defender}!',
      '{attacker}\'s {move} is PRECISION STRIKING WITH POWER!',
      '{defender} is hurt badly by that {move}!',
      'A POWERFUL element in that {move}!',
      'The {move} from {attacker} is DAMAGING!',
      '{defender} is staggered significantly!',
      'SERIOUS DAMAGE! That {move} from {attacker} was VICIOUS!',
      'The {move} lands with POWER!',
      '{attacker}\'s {move} is a STATEMENT!',
      'The {move} from {attacker} breaks {defender}\'s rhythm!',
    ],
    CRITICAL_HIT: [
      'THAT IS A DEVASTATING BLOW! {attacker}\'s {move} catches {defender} FLUSH!',
      '{defender} IS IN SERIOUS TROUBLE! The {move} from {attacker} is PRECISION!',
      'CRITICAL DAMAGE! A {move} of TREMENDOUS POWER!',
      'THE {move} FROM {attacker} IS ABSOLUTELY LETHAL!',
      '{defender} IS HURT BADLY! {attacker}\'s {move} is CATASTROPHIC!',
      'THE REFEREE MAY NEED TO STEP IN! {attacker}\'s {move} is DEVASTATING!',
      'THAT\'S A POTENTIAL FINISHING BLOW! The {move} from {attacker}!',
      '{defender} IS COMPROMISED AFTER THAT {move}!',
      'CRITICAL CONDITION! {attacker}\'s {move} lands FLUSH!',
      'THE {move} IS A SHOW OF SUPERIOR TECHNIQUE!',
      'SPECTACULAR FINISH INCOMING? {attacker}\'s {move}!',
      'THE {move} FROM {attacker} IS CHAMPIONSHIP-LEVEL STRIKING!',
      '{defender} seems to be FADING from {attacker}\'s {move}!',
      'IS THIS THE TURNING POINT? {attacker}\'s {move}!',
      'THAT {move} FROM {attacker} COULD DECIDE THIS FIGHT!',
      'THE PRECISION! THE POWER! {attacker}\'s {move} lands PERFECTLY!',
      '{defender} IS ON THE BRINK! The {move} was DEVASTATING!',
      'THE {move} FROM {attacker} IS A STATEMENT!',
      'CRITICAL HIT! {attacker}\'s {move} lands WITH AUTHORITY!',
      'THE FIGHT COULD BE OVER! {attacker}\'s {move} is OVERWHELMING!',
      'THAT IS A CHAMPIONSHIP {move} FROM {attacker}!',
      '{defender} IS SEVERELY HURT! THE {move} WAS MERCILESS!',
      'THE {move} FROM {attacker} IS AN EXECUTION!',
      'WILL {defender} SURVIVE THIS? {attacker}\'s {move} is FATAL!',
      'THE {move} FROM {attacker} IS MATCH-CHANGING!',
      'THE REFEREE IS WATCHING CLOSELY! {attacker}\'s {move}!',
      'THAT {move} FROM {attacker} COULD CHANGE EVERYTHING!',
      'THE {move} IS A TECHNICAL MASTERPIECE!',
      'CRITICAL DAMAGE! {attacker} HAS {defender} ON THE BRINK!',
      'THIS IS IT! {attacker}\'s {move} MIGHT BE THE END!',
    ],
    FINISHER: [
      '{attacker} DELIVERS A FINISHING {move}! {defender} IS DOWN!',
      'KNOCKOUT! {attacker}\'s {move} IS ABSOLUTELY DEVASTATING!',
      'IT\'S OVER! THE {move} FROM {attacker} ENDS THIS!',
      '{defender} IS FINISHED! THE {move} FROM {attacker} IS FINAL!',
      'THE {move} FROM {attacker}—THAT IS A KNOCKOUT!',
      'LIGHTS OUT! {attacker}\'s {move} HAS DONE IT!',
      'THE REFEREE STEPS IN! {attacker}\'s {move} HAS ENDED THIS FIGHT!',
      '{defender} IS OUT! {attacker} WINS WITH A BRUTAL {move}!',
      'MATCH OVER! THE {move} FROM {attacker} IS FINAL!',
      'SUBMISSION INCOMING! {attacker}\'s {move} HAS FORCED THE ISSUE!',
      '{attacker} SECURES VICTORY! THE {move} WAS IMMACULATE!',
      'THIS IS CHAMPIONSHIP-LEVEL FINISHING TECHNIQUE!',
      'THE {move} FROM {attacker} IS AN INSTANT CLASSIC!',
      'FIGHT ENDS NOW! {defender} CANNOT CONTINUE!',
      'THE {move}—A MASTERCLASS IN KNOCKOUT POWER!',
      '{attacker} DOMINATED THE FINISH! THE {move} IS PERFECT!',
      '{defender} HAS NO ANSWER! THE {move} FROM {attacker}!',
      'THE WINNING {move} FROM {attacker}!',
      '{attacker} SHOWS SUPREME STRIKING! THE {move} ENDS ALL DEBATE!',
      'THIS IS A STATEMENT VICTORY! THE {move} FROM {attacker}!',
      'THE FINISHING SEQUENCE FROM {attacker} IS PERFECTION!',
      '{defender} IS NO LONGER ABLE TO DEFEND! {attacker} WINS!',
      'THAT IS ELITE-LEVEL COMBAT TECHNIQUE!',
      'THE {move} FROM {attacker} WILL BE REPLAYED FOR YEARS!',
      '{attacker} IS THE VICTOR! AN OUTSTANDING FINISH!',
      'THE SKILL, THE TIMING, THE POWER—{attacker} SHOWS IT ALL!',
      'A COMPLETE AND DOMINANT VICTORY FOR {attacker}!',
      'THE {move} ENDS THIS CONTEST DECISIVELY!',
      'WHAT A FINISH! {attacker} IS TRIUMPHANT!',
      '{defender} IS DEFEATED! {attacker} STANDS VICTORIOUS!',
    ],
  },
  cs: {
    MISS: [
      '{attacker} míří vysoko nad hlavu soupeře {defender}!',
      'Nic! {attacker} se netrefil s útokem {move}!',
      '{defender} nebyl ani v nebezpečí. Úder {move} minul.',
      '{attacker} provádí {move}, ale {defender} tam už není.',
      'Špatné načasování. {move} od {attacker} se netrefil.',
      '{attacker} zaostává s {move}!',
      'Plátno dostává ránu místo {defender}!',
      '{attacker} střílí přes cíl s {move}.',
      'Mimo! {move} od {attacker} nenašel cíl.',
      'Telegrafovaný {move} od {attacker} nachází jen vzduch.',
      '{defender} čte {move} a uhne stranou.',
      '{move} od {attacker} je skvěle vykrytý hráčem {defender}.',
      'Žádný účinek. {move} se dal snadno vyhnout.',
      '{attacker} vyslal {move} s nedostatečným dosahem.',
      '{move} míjí {defender} o pár centimetrů.',
      'Pokus o {move} od {attacker} selhal.',
      'Dobrá práce nohou od {defender} vyhýbá se {move}.',
      '{move} se netrefil. {defender} je nedotčený.',
      '{attacker} se předřel s {move}.',
      'Neúčinné řízení dosahu u {move}.',
      '{defender} nikdy nebyl ohrožen tímto {move}.',
      '{move} od {attacker} byl špatně umístěn.',
      'Nic z toho. {attacker} se úplně mine s {move}.',
      '{attacker} máchá a míjí s {move}.',
      '{defender} se tomu úplně vyhnul!',
      'Ten {move} se mohl vůbec nestát.',
      'Pozice {defender} porazila {move}.',
      '{attacker} potřebuje lepší načasování u {move}.',
      'Dokonce rozhodčí zívá u mineného {move}.',
      'Ten {move} od {attacker} má nulový dopad.',
    ],
    DODGE: [
      '{defender} unikl {move} s výjimečnou prací nohou!',
      'Brilantní pohyb hlavy od {defender}!',
      '{move} od {attacker} je těsně vyhnout.',
      '{defender} se sehnul pod přilétající {move}.',
      'Výborný únik! {defender} četl {move} od {attacker}.',
      '{defender} se válí a vyhýbá {move}.',
      '{attacker} útočí, ale {defender} se pohybuje.',
      'Rychlý postranní pohyb od {defender} vyhýbá se {move}.',
      '{defender} projevuje obranné povědomí, vyhýbá se {move}.',
      'Ten {move} svíští kolem ucha {defender}!',
      '{defender} se proklouzne dovnitř a vyhne se {move}.',
      'Výbušná práce nohou od {defender}!',
      '{defender} paríruje a vyhýbá se {move}.',
      '{move} od {attacker} je poražen pohybem {defender}.',
      '{defender} předvídá {move} perfektně.',
      'Čistá úderná obrana od {defender}!',
      '{defender} couvá od {move}.',
      'Mistrovské vyhýbání! {move} byl vyhnout.',
      '{defender} používá řízení vzdálenosti perfektně.',
      '{move} od {attacker} byl čten jako kniha.',
      'Dokonalý pohyb hlavy od {defender}!',
      'Povědomí o ringu {defender} brání {move}.',
      '{move} nenachází cíl.',
      '{defender} dělá z {attacker} blázna.',
      'Obranná mistrovská třída od {defender}!',
      'Ten {move} byl telegrafován!',
      '{defender} reaguje s dokonalou pozicí.',
      '{move} nemůže trefit proti takové obraně.',
      '{defender} mění úhel a vyhýbá se.',
      'Podrobné vyhýbání od {defender}!',
    ],
    LIGHT_HIT: [
      '{move} od {attacker} lehce zasáhl paži {defender}.',
      'Lehký kontakt od {move} {attacker}.',
      '{move} od {attacker} se trefil, ale {defender} to pohltil.',
      'Dotykový {move} od {attacker} dosáhl {defender}.',
 '{defender} pociťuje minimální poškození od {move}.',
      '{move} od {attacker} trefil cíl lehce.',
      'Částečné spojení u {move} od {attacker}.',
      '{defender} dostane lehkou ránu od {move} {attacker}.',
      'Minimální poškození od {move} {attacker}.',
      '{move} od {attacker} přistál, ale chybí síla.',
      'Pouze dotykový kontakt u toho {move}.',
      '{defender} odmítl lehký {move}.',
      'Ne významné poškození od {move} {attacker}.',
      '{attacker} se spojuje s lehkým {move}.',
      'Menší poškození způsobené {move} {attacker}.',
      '{move} našel {defender}, sotva.',
      '{defender} je minimálně ovlivněn.',
      'Pozice {attacker} registruje kontakt.',
      'Měkký {move} od {attacker} kontaktuje.',
      'Povrchové poškození od {move} {attacker}.',
      '{move} od {attacker} skóruje menší bod.',
      '{defender} pohltil lehký {move}.',
      'Neúčinné úderání od {attacker}.',
      'Opatrný {move} od {attacker}.',
      '{defender} přijímá lehkou ránu a jede vpřed.',
      'Měkký, ale kontrolovaný kontakt od {attacker}.',
      '{defender} je obtěžován, ale ne zraněn.',
      '{attacker} přistává lehce na {defender}.',
      'Skórovací kontakt bez síly.',
      'Ten {move} registruje pouze na kartách rozhodčích.',
    ],
    MEDIUM_HIT: [
      '{attacker} se spojuje se solidním {move} na {defender}!',
      'Dobrý kontakt! {move} od {attacker} přistál čistě.',
      '{defender} to pociťuje - {move} od {attacker}!',
      '{move} od {attacker} mírně pohodí hlavu {defender}.',
      'Účinné úderání! {move} přistál čtvercově na {defender}.',
      '{attacker} načasoval {move} perfektně.',
      'Ten {move} má plnou pozornost {defender}!',
      '{defender} dostává solidní {move} do těla.',
      '{move} od {attacker} vytváří separaci.',
      'Čisté úderání od {attacker}! {move} se spojuje krásně.',
      '{attacker} přistává {move} s autoritou.',
      'Značné poškození způsobené {move} {attacker}!',
      '{defender} lehce zakolyše od {move}.',
      '{move} od {attacker} je perfektně proveden.',
      'Skutečná síla za tím {move} od {attacker}!',
      '{defender} je otřesena {move} {attacker}!',
      '{move} od {attacker} má vážný dopad!',
      '{defender} krčí od {move}.',
      '{attacker} přistává taktický {move} na {defender}.',
      'Působivá technika u toho {move}!',
      '{move} od {attacker} je učebnicové provedení.',
      '{defender} pohltil podstatný {move}.',
      'Kvalitní úderání ukázané {attacker}!',
      '{attacker} načasování a vzdálenosti perfektně.',
      'Viditelný dopad od toho {move}!',
      'Ten {move} bude hromadit značné poškození!',
      '{defender} kývá - pocítil ten {move}.',
      'Profesionální úderání od {attacker}!',
      '{move} registruje jasně na {defender}.',
      'Učebnicová forma u toho {move}!',
    ],
    HEAVY_HIT: [
      'DEVASTUJÍCÍ {move} od {attacker} otřásá {defender}!',
      '{defender} je těžce zraněn! {move} od {attacker} přistane s vážnou silou!',
      'OBROVSKÝ DOPAD! {move} od {attacker} zakolyse {defender}!',
      '{defender} je viditelně otřesen {move}!',
      'Ten {move} od {attacker} je VÝKONNÝ!',
      '{attacker} uvolňuje {move} s plnou silou na {defender}!',
      '{move} od {attacker} je naprosto BRUTÁLNÍ!',
      '{defender} se prohýbá pod silou {move}!',
      'VELKÉ POŠKOZENÍ! {move} od {attacker} je RÁN A!',
      '{attacker} se spojuje s HROMADNÝM {move}!',
      '{move} přistává S AUTORITOU!',
      '{defender} je tvrdě otřesen {move}!',
      'DESTRUKTIVNÍ {move} od {attacker} přistane čtvercově!',
      '{move} od {attacker} má {defender} v problémech!',
      'ZNAČNÉ POŠKOZENÍ ZPŮSOBENÉ! {move} od {attacker} je NÁSILNÝ!',
      '{defender} je jasně ovlivněn - ten {move} byl TVRDÝ!',
      '{move} od {attacker} nese OBROVSKOU SÍLU!',
      '{defender} je otřesen! {move} byl PODSTATNÝ!',
      'TRESTAJÍCÍ {move} od {attacker}!',
      '{attacker} přistává DRÁSAJÍCÍ {move}!',
      'Dopad {move} je EVIDENTNÍ na {defender}!',
      '{move} od {attacker} je PRECIZNÍ ÚDERÁNÍ S SILOU!',
      '{defender} je těžce zraněn tím {move}!',
      'VÝKONNÝ prvek v tom {move}!',
      '{move} od {attacker} je POŠKOZUJÍCÍ!',
      '{defender} je významně zakolysan!',
      'VÁŽNÉ POŠKOZENÍ! Ten {move} od {attacker} byl ZLÝ!',
      '{move} přistává se SILOU!',
      '{move} od {attacker} je PROHLÁŠENÍ!',
      '{move} od {attacker} zlomil rytmus {defender}!',
    ],
    CRITICAL_HIT: [
      'TO JE DEVASTUJÍCÍ ÚDER! {move} od {attacker} chytá {defender} FLUSH!',
      '{defender} JE V VÁŽNÝCH POTÍŽÍCH! {move} od {attacker} je PŘESNOST!',
      'KRITICKÉ POŠKOZENÍ! {move} OBROVSKÉHO VÝKONU!',
      '{move} OD {attacker} JE NAPROSTO SMRTELNÝ!',
      '{defender} JE TĚŽCE ZRANĚN! {move} od {attacker} je KATASTROFICKÝ!',
      'ROZHODČÍ MOŽNÁ MUSÍ VSTOUPIT! {move} od {attacker} je DEVASTUJÍCÍ!',
      'TO JE POTENCIÁLNÍ DOKONČOVACÍ ÚDER! {move} od {attacker}!',
      '{defender} JE KOMPROMITOVÁN PO TOM {move}!',
      'KRITICKÝ STAV! {move} od {attacker} přistává FLUSH!',
      '{move} JE UKÁZKA VYNIKAJÍCÍ TECHNIKY!',
      'SPEKTAKULÁRNÍ DOKONČENÍ PŘICHÁZÍ? {move} od {attacker}!',
      '{move} OD {attacker} JE ÚDERÁNÍ NA ÚROVNI ŠAMPIONÁTU!',
      '{defender} se zdá být BLEDÝ od {move} {attacker}!',
      'JE TO OTOČNÝ BOD? {move} od {attacker}!',
      'TEN {move} OD {attacker} MŮŽE ROZHODNOUT TENTO BOJ!',
      'PŘESNOST! SÍLA! {move} od {attacker} přistává PERFEKTNĚ!',
      '{defender} JE NA OKRAJI! {move} byl DEVASTUJÍCÍ!',
      '{move} OD {attacker} JE PROHLÁŠENÍ!',
      'KRITICKÝ ZÁSAH! {move} od {attacker} přistává S AUTORITOU!',
      'BOJ MŮŽE BÝT PŘES! {move} od {attacker} je OVERWHELMUJÍCÍ!',
      'TO JE ŠAMPIONSKÝ {move} OD {attacker}!',
      '{defender} JE TĚŽCE ZR ANĚN! {move} BYL NELÍTOSTNÝ!',
      '{move} OD {attacker} JE POPRAVA!',
      'PŘEŽIJE {defender} TO? {move} od {attacker} je FATÁLNÍ!',
      '{move} OD {attacker} JE MĚNÍCÍ ZÁP!',
      'ROZHODČÍ SLEDUJE POZORNĚ! {move} od {attacker}!',
      'TEN {move} OD {attacker} MŮŽE ZMĚNIT VŠE!',
      '{move} JE TECHNICKÉ MISTROVSKÉ DÍLO!',
      'KRITICKÉ POŠKOZENÍ! {attacker} MÁ {defender} NA OKRAJI!',
      'TO JE TO! {move} od {attacker} MŮŽE BÝT KONEC!',
    ],
    FINISHER: [
      '{attacker} DODÁVÁ DOKONČOVACÍ {move}! {defender} JE DOLE!',
      'KNOCKOUT! {move} od {attacker} JE NAPROSTO DEVASTUJÍCÍ!',
      'JE TO PŘES! {move} OD {attacker} TO KONČÍ!',
      '{defender} JE HOTOVÝ! {move} OD {attacker} JE FINÁLNÍ!',
      '{move} OD {attacker} - TO JE KNOCKOUT!',
      'SVĚTLA VENKU! {move} od {attacker} TO UDĚLAL!',
      'ROZHODČÍ VSTUPUJE! {move} od {attacker} UKONČIL TENTO BOJ!',
      '{defender} JE VENKU! {attacker} VYHRÁVÁ S BRUTÁLNÍM {move}!',
      'ZÁP PŘES! {move} OD {attacker} JE FINÁLNÍ!',
      'SUBMISE PŘICHÁZÍ! {move} od {attacker} VYNUTIL PROBLÉM!',
      '{attacker} ZAJISTUJE VÍTĚZSTVÍ! {move} BYL NEPOSKVRNĚNÝ!',
      'TO JE DOKONČOVACÍ TECHNIKA NA ÚROVNI ŠAMPIONÁTU!',
      '{move} OD {attacker} JE OKAMŽITÁ KLASIKA!',
      'BOJ KONČÍ TEĎE! {defender} NEMŮŽE POKRAČOVAT!',
      '{move} - MISTROVSKÁ TŘÍDA V KNOCKOUT SÍLE!',
      '{attacker} DOMINOVAL DOKONČENÍ! {move} JE PERFEKTNÍ!',
      '{defender} NEMÁ ODPOVĚĎ! {move} OD {attacker}!',
      'VÍTĚZNÝ {move} OD {attacker}!',
      '{attacker} UKAZUJE SUPREME ÚDERÁNÍ! {move} KONČÍ VŠECHNU DEBATU!',
      'TO JE PROHLÁŠENÍ VÍTĚZSTVÍ! {move} OD {attacker}!',
      'DOKONČOVACÍ SEKVENCE OD {attacker} JE DOKONALOST!',
      '{defender} UŽ NENÍ SCHOPEN OBRÁNIT! {attacker} VYHRÁVÁ!',
      'TO JE ÉLITNÍ BOJOVÁ TECHNIKA!',
      '{move} OD {attacker} BUDE PŘEHRÁVÁN ROKY!',
      '{attacker} JE VÍTĚZ! VYNIKAJÍCÍ DOKONČENÍ!',
      'DOVEDNOST, NAČASOVÁNÍ, SÍLA - {attacker} UKAZUJE VŠE!',
      'ÚPLNÉ A DOMINANTNÍ VÍTĚZSTVÍ PRO {attacker}!',
      '{move} KONČÍ TUTO SOUTĚŽ ROZHODNĚ!',
      'CO ZA DOKONČENÍ! {attacker} JE TRIUMFUJÍCÍ!',
      '{defender} JE PORAŽEN! {attacker} STOJÍ VÍTĚZNĚ!',
    ],
  },
  pl: {
    MISS: [
      '{move} od {attacker} przelatuje wysoko nad głową {defender}!',
      'Brak kontaktu! {attacker} całkowicie chybił {move}!',
      '{defender} nigdy nie był w niebezpieczeństwie. {move} chybił czysto.',
      '{attacker} wykonuje {move}, ale {defender} tam nie ma.',
      'Zły timing. {move} od {attacker} nie trafia.',
      '{move} od {attacker} jest za krótki o pełny dystans.',
      'Płótno dostaje uderzenie zamiast {defender}!',
      '{attacker} przesadza z {move}.',
      'Szeroko! {move} od {attacker} nie znajduje celu.',
      'Telegrafowany {move} od {attacker} znajduje tylko powietrze.',
      '{defender} czyta {move} i odchodzi na bok.',
      '{move} od {attacker} jest dobrze unikany przez {defender}.',
      'Brak efektu. {move} jest całkowicie uniknięty.',
      '{attacker} rzuca {move} z niewystarczającym zasięgiem.',
      '{move} mija {defender} o centymetry.',
      'Próba {move} od {attacker} nie udała się.',
      'Dobrze czasowana praca nóg od {defender} unika {move}.',
      '{move} nie trafia. {defender} jest nietknięty.',
      '{attacker} przesadza na {move}.',
      'Nieskuteczne zarządzanie zasięgiem przy {move}.',
      '{defender} nigdy nie był zagrożony tym {move}.',
      '{move} od {attacker} był źle umieszczony.',
      'Nie ma szans. {move} od {attacker} całkowicie chybił.',
      '{attacker} szw ankuje i chybia z {move}.',
      'Całkowicie uniknięte przez {defender}!',
      'Ten {move} mógł się nie wydarzyć.',
      'Pozycja {defender} pokonała {move}.',
      '{attacker} potrzebuje lepszego timingu na tym {move}.',
      'Nawet sędzia ziewa przy tym chybionym {move}.',
      'Ten {move} od {attacker} rejestruje zero wpływu.',
    ],
    DODGE: [
      '{defender} unika {move} z wyjątkową pracą nóg!',
      'Genialny ruch głowy od {defender}!',
      '{move} od {attacker} jest wąsko uniknięty.',
      '{defender} kuca pod nadlatującym {move}.',
      'Doskonałe unikanie! {defender} czyta {move} od {attacker}.',
      '{defender} toczy się i unika {move}.',
      '{attacker} atakuje, ale {defender} się porusza.',
      'Szybki ruch boczny od {defender} unika {move}.',
      '{defender} wykazuje świadomość obronną, unikając {move}.',
      'Ten {move} gwiżdże obok ucha {defender}!',
      '{defender} wślizguje się i unika {move}.',
      'Wybuchowa praca nóg od {defender}!',
      '{defender} paruje i unika {move}.',
      '{move} od {attacker} pokonany ruchem {defender}.',
      '{defender} przewiduje {move} perfekcyjnie.',
      'Czysta obrona uderzeniowa od {defender}!',
      '{defender} cofa się od {move}.',
      'Mistrzowskie unikanie! {move} został uniknięty.',
      '{defender} używa zarządzania dystansem perfekcyjnie.',
      '{move} od {attacker} został przeczytany jak książka.',
      'Idealny ruch głowy od {defender}!',
      'Świadomość ringu {defender} zapobiega {move}.',
      '{move} nie znajduje celu.',
      '{defender} robi z {attacker} głupca.',
      'Obronna klasa mistrzowska od {defender}!',
      'Ten {move} był telegrafowany!',
      '{defender} reaguje z doskonałą pozycją.',
      '{move} nie może trafić przeciwko takiej obronie.',
      '{defender} zmienia kąt i unika.',
      'Podręcznikowe unikanie od {defender}!',
    ],
    LIGHT_HIT: [
      '{move} od {attacker} lekko trafia ramię {defender}.',
      'Lekki kontakt od {move} {attacker}.',
      '{move} od {attacker} trafia, ale {defender} pochłania.',
      'Dotykowy {move} od {attacker} osiąga {defender}.',
      '{defender} odczuwa minimalne obrażenia od {move}.',
      '{move} od {attacker} znajduje cel lekko.',
      'Częściowe połączenie na {move} od {attacker}.',
      '{defender} dostaje lekki strzał od {move} {attacker}.',
      'Minimalne obrażenia od {move} {attacker}.',
      '{move} od {attacker} ląduje, ale brakuje mocy.',
      'Dotykowy kontakt od tego {move}.',
      '{defender} odrzucił lekki {move}.',
      'Nie znaczące obrażenia od {move} {attacker}.',
      '{attacker} łączy się z lekkim {move}.',
      'Mniejsze obrażenia zadane przez {move} {attacker}.',
      '{move} znalazł {defender}, ledwo.',
      '{defender} jest minimalnie dotknięty.',
      'Pozycja {attacker} rejestruje kontakt.',
      'Miękki {move} od {attacker} kontaktuje.',
      'Powierzchniowe obrażenia od {move} {attacker}.',
      '{move} od {attacker} zdobywa mniejszy punkt.',
      '{defender} pochłonął lekki {move}.',
      'Nieskuteczne uderzanie od {attacker}.',
      'Ostrożny {move} od {attacker}.',
      '{defender} przyjmuje lekkie uderzenie i jedzie naprzód.',
      'Miękki, ale kontrolowany kontakt od {attacker}.',
      '{defender} jest zaniepokojony, ale nie zraniony.',
      '{attacker} ląduje lekko na {defender}.',
      'Punktujący kontakt bez mocy.',
      'Ten {move} rejestruje tylko na kartach sędziów.',
    ],
    MEDIUM_HIT: [
      '{attacker} łączy się z solidnym {move} na {defender}!',
      'Dobry kontakt! {move} od {attacker} wylądował czysto.',
      '{defender} czuje ten {move} od {attacker}!',
      '{move} od {attacker} lekko odrzuca głową {defender}.',
      'Skuteczne uderzanie! {move} wylądował kwadratowo na {defender}.',
      '{attacker} czasował {move} perfekcyjnie.',
      'Ten {move} ma pełną uwagę {defender}!',
      '{defender} dostaje solidny {move} do ciała.',
      '{move} od {attacker} tworzy separację.',
      'Czyste uderzanie od {attacker}! {move} łączy się pięknie.',
      '{attacker} wyląduje {move} z autorytetem.',
      'Znaczące obrażenia zadane przez {move} {attacker}!',
      '{defender} lekko zatacza się od {move}.',
      '{move} od {attacker} jest perfekcyjnie wykonany.',
      'Prawdziwa moc za tym {move} od {attacker}!',
      '{defender} jest wstrząśnięty {move} {attacker}!',
      '{move} od {attacker} ma poważny wpływ!',
      '{defender} krzyczy od {move}.',
      '{attacker} wyląduje taktyczny {move} na {defender}.',
      'Imponująca technika na tym {move}!',
      '{move} od {attacker} jest podręcznikowym wykonaniem.',
      '{defender} pochłonął znaczny {move}.',
      'Jakościowe uderzanie wykazane przez {attacker}!',
      '{attacker} czasowanie i odległości perfekcyjnie.',
      'Widoczny wpływ od tego {move}!',
      'Ten {move} będzie kumulować znaczące obrażenia!',
      '{defender} kiwa - poczuł ten {move}.',
      'Profesjonalne uderzanie od {attacker}!',
      '{move} rejestruje wyraźnie na {defender}.',
      'Podręcznikowa forma na tym {move}!',
    ],
    HEAVY_HIT: [
      'NISZCZĄCY {move} od {attacker} wstrząsa {defender}!',
      '{defender} jest ciężko zraniony! {move} od {attacker} ląduje z poważną siłą!',
      'OGROMNY WPŁYW! {move} od {attacker} zatacza {defender}!',
      '{defender} jest widocznie wstrząśnięty {move}!',
      'Ten {move} od {attacker} jest POTĘŻNY!',
      '{attacker} uwalnia {move} z pełną siłą na {defender}!',
      '{move} od {attacker} jest absolutnie BRUTALNY!',
      '{defender} ugina się pod siłą {move}!',
      'WIĘKSZE OBRAŻENIA! {move} od {attacker} jest STRZAŁEM!',
      '{attacker} łączy się z GRZMIĄCYM {move}!',
      '{move} ląduje Z AUTORYTETEM!',
      '{defender} jest mocno wstrząśnięty {move}!',
      'DESTRUKCYJNY {move} od {attacker} ląduje kwadratowo!',
      '{move} od {attacker} ma {defender} w kłopotach!',
      'ZNACZĄCE OBRAŻENIA ZADANE! {move} od {attacker} jest GWAŁTOWNY!',
      '{defender} jest wyraźnie dotknięty - ten {move} był TWARDY!',
      '{move} od {attacker} niesie OGROMNĄ SIŁĘ!',
      '{defender} jest wstrząśnięty! {move} był ZNACZNY!',
      'KARAJĄCY {move} od {attacker}!',
      '{attacker} ląduje MIAŻDŻĄCY {move}!',
      'Wpływ {move} jest EWIDENTNY na {defender}!',
      '{move} od {attacker} jest PRECYZYJNYM UDERZANIEM Z MOCĄ!',
      '{defender} jest ciężko zraniony tym {move}!',
      'POTĘŻNY element w tym {move}!',
      '{move} od {attacker} jest USZKADZAJĄCY!',
      '{defender} jest znacznie zataczany!',
      'POWAŻNE OBRAŻENIA! Ten {move} od {attacker} był ZŁY!',
      '{move} ląduje z MOCĄ!',
      '{move} od {attacker} jest OŚWIADCZENIEM!',
      '{move} od {attacker} łamie rytm {defender}!',
    ],
    CRITICAL_HIT: [
      'TO JEST NISZCZĄCY CIOS! {move} od {attacker} łapie {defender} FLUSH!',
      '{defender} JEST W POWAŻNYCH KŁOPOTACH! {move} od {attacker} jest PRECYZJĄ!',
      'KRYTYCZNE OBRAŻENIA! {move} OGROMNEJ MOCY!',
      '{move} OD {attacker} JEST ABSOLUTNIE ŚMIERTELNY!',
      '{defender} JEST CIĘŻKO ZRANIONY! {move} od {attacker} jest KATASTROFICZNY!',
      'SĘDZIA MOŻE MUSIEĆ WKROCZYĆ! {move} od {attacker} jest NISZCZĄCY!',
      'TO JEST POTENCJALNY KOŃCZĄCY CIOS! {move} od {attacker}!',
      '{defender} JEST SKOMPROMITOWANY PO TYM {move}!',
      'STAN KRYTYCZNY! {move} od {attacker} ląduje FLUSH!',
      '{move} JEST POKAZEM WYŻSZ EJ TECHNIKI!',
      'SPEKTAKULARNY KONIEC NADCHODZI? {move} od {attacker}!',
      '{move} OD {attacker} JEST UDERZANIEM NA POZIOMIE MISTRZOWSKIM!',
      '{defender} wydaje się BLEDNĄĆ od {move} {attacker}!',
      'CZY TO PUNKT ZWROTNY? {move} od {attacker}!',
      'TEN {move} OD {attacker} MOŻE ZADECYDOWAĆ TĘ WALKĘ!',
      'PRECYZJA! MOC! {move} od {attacker} ląduje PERFEKCYJNIE!',
      '{defender} JEST NA SKRAJU! {move} był NISZCZĄCY!',
      '{move} OD {attacker} JEST OŚWIADCZENIEM!',
      'KRYTYCZNE OBRAŻENIA! {move} od {attacker} ląduje Z AUTORYTETEM!',
      'WALKA MOŻE BYĆ SKOŃCZONA! {move} od {attacker} jest PRZYTŁACZAJĄCY!',
      'TO JEST MISTRZOWSKI {move} OD {attacker}!',
      '{defender} JEST CIĘŻKO ZRANIONY! {move} BYŁ BEZLITOSNY!',
      '{move} OD {attacker} JEST EGZEKUCJĄ!',
      'CZY {defender} PRZEŻYJE TO? {move} od {attacker} jest FATALNY!',
      '{move} OD {attacker} ZMIENIA WALKĘ!',
      'SĘDZIA OBSERWUJE UWAŻNIE! {move} od {attacker}!',
      'TEN {move} OD {attacker} MOŻE ZMIENIĆ WSZYSTKO!',
      '{move} JEST TECHNICZNYM ARCYDZIEŁEM!',
      'KRYTYCZNE OBRAŻENIA! {attacker} MA {defender} NA SKRAJU!',
      'TO JEST TO! {move} od {attacker} MOŻE BYĆ KONIEC!',
    ],
    FINISHER: [
      '{attacker} ODDAJE KOŃCZĄCY {move}! {defender} JEST W DOLE!',
      'NOKAUT! {move} od {attacker} JEST ABSOLUTNIE NISZCZĄCY!',
      'TO KONIEC! {move} OD {attacker} TO KOŃCZY!',
      '{defender} JEST SKOŃCZONY! {move} OD {attacker} JEST FINALNY!',
      '{move} OD {attacker} - TO JEST NOKAUT!',
      'ŚWIATŁA ZGASŁY! {move} od {attacker} TO ZROBIŁ!',
      'SĘDZIA WKRACZA! {move} od {attacker} ZAKOŃCZYŁ TĘ WALKĘ!',
      '{defender} JEST WYŁĄCZONY! {attacker} WYGRYWA Z BRUTALNYM {move}!',
      'WALKA KONIEC! {move} OD {attacker} JEST FINALNY!',
      'PODDANIE NADCHODZI! {move} od {attacker} WYMUSIŁ PROBLEM!',
      '{attacker} ZAPEWNIA ZWYCIĘSTWO! {move} BYŁ NIESKAZITELNY!',
      'TO JEST TECHNIKA KOŃCZĄCA NA POZIOMIE MISTRZOWSKIM!',
      '{move} OD {attacker} JEST NATYCHMIASTOWĄ KLASYKĄ!',
      'WALKA KOŃCZY SIĘ TERAZ! {defender} NIE MOŻE KONTYNUOWAĆ!',
      '{move} - KLASA MISTRZOWSKA W MOCY NOKAUTU!',
      '{attacker} DOMINOWAŁ KONIEC! {move} JEST PERFEKCYJNY!',
      '{defender} NIE MA ODPOWIEDZI! {move} OD {attacker}!',
      'ZWYCIĘSKI {move} OD {attacker}!',
      '{attacker} POKAZUJE NAJWYŻSZE UDERZANIE! {move} KOŃCZY CAŁĄ DEBATĘ!',
      'TO JEST OŚWIADCZENIE ZWYCIĘSTWA! {move} OD {attacker}!',
      'SEKWENCJA KOŃCZĄCA OD {attacker} JEST PERFEKCYJNA!',
      '{defender} NIE JEST JUŻ W STANIE BRONIĆ! {attacker} WYGRYWA!',
      'TO JEST TECHNIKA BOJOWA NA POZIOMIE ELITARNYM!',
      '{move} OD {attacker} BĘDZIE ODTWARZANY PRZEZ LATA!',
      '{attacker} JEST ZWYCIĘZCĄ! WYBITNE ZAKOŃCZENIE!',
      'UMIEJĘTNOŚĆ, TIMING, MOC - {attacker} POKAZUJE WSZYSTKO!',
      'KOMPLETNE I DOMINUJĄCE ZWYCIĘSTWO DLA {attacker}!',
      '{move} KOŃCZY TĘ RYWALIZACJĘ ZDECYDOWANIE!',
      'CO ZA KONIEC! {attacker} JEST TRIUMFUJĄCY!',
      '{defender} JEST POKONANY! {attacker} STOI ZWYCIĘSKO!',
    ],
  },
};

/**
 * Get a random phrase from a category for a specific language
 */
export const getRandomPhrase = (category: BattleCategory, language: Language = 'en'): string => {
  const phrases = BATTLE_DATA[language][category];
  return phrases[Math.floor(Math.random() * phrases.length)];
};

/**
 * Replace placeholders in a phrase with actual values
 */
export const formatPhrase = (
  phrase: string,
  attacker: string,
  defender: string,
  move: string
): string => {
  return phrase
    .replace(/{attacker}/g, attacker)
    .replace(/{defender}/g, defender)
    .replace(/{move}/g, move);
};

/**
 * Get a formatted battle message for a specific language
 */
export const getBattleMessage = (
  category: BattleCategory,
  attacker: string,
  defender: string,
  move: string,
  language: Language = 'en'
): string => {
  const phrase = getRandomPhrase(category, language);
  return formatPhrase(phrase, attacker, defender, move);
};
