import { LeaderboardEntry, getLeagueFromReputation } from '../types';

export const LEADERBOARD_FIGHTERS: LeaderboardEntry[] = [
  {
    id: 'ai_1',
    name: 'Alexander Volkov',
    nickname: 'The Russian Bear',
    record: { wins: 47, losses: 3, draws: 1 },
    reputation: 4700,
    level: 45,
    league: getLeagueFromReputation(4700),
    avatarEmoji: '🐻',
  },
  {
    id: 'ai_2',
    name: 'Kenji Tanaka',
    nickname: 'The Tsunami',
    record: { wins: 42, losses: 5, draws: 2 },
    reputation: 4200,
    level: 42,
    league: getLeagueFromReputation(4200),
    avatarEmoji: '🌊',
  },
  {
    id: 'ai_3',
    name: 'Diego Reyes',
    nickname: 'El Fuego',
    record: { wins: 38, losses: 8, draws: 1 },
    reputation: 3800,
    level: 38,
    league: getLeagueFromReputation(3800),
    avatarEmoji: '🔥',
  },
  {
    id: 'ai_4',
    name: 'Jade Chen',
    nickname: 'Dragon Striker',
    record: { wins: 35, losses: 7, draws: 3 },
    reputation: 3500,
    level: 35,
    league: getLeagueFromReputation(3500),
    avatarEmoji: '🐉',
  },
  {
    id: 'ai_5',
    name: 'Marcus Johnson',
    nickname: 'The Machine',
    record: { wins: 32, losses: 9, draws: 2 },
    reputation: 3200,
    level: 32,
    league: getLeagueFromReputation(3200),
    avatarEmoji: '⚙️',
  },
  {
    id: 'ai_6',
    name: 'Sofia Petrov',
    nickname: 'Ice Queen',
    record: { wins: 28, losses: 12, draws: 1 },
    reputation: 2800,
    level: 28,
    league: getLeagueFromReputation(2800),
    avatarEmoji: '❄️',
  },
  {
    id: 'ai_7',
    name: 'Carlos Santos',
    nickname: 'The King',
    record: { wins: 24, losses: 16, draws: 3 },
    reputation: 2400,
    level: 24,
    league: getLeagueFromReputation(2400),
    avatarEmoji: '👑',
  },
  {
    id: 'ai_8',
    name: 'Isabella Romano',
    nickname: 'Rose of Rome',
    record: { wins: 21, losses: 18, draws: 2 },
    reputation: 2100,
    level: 21,
    league: getLeagueFromReputation(2100),
    avatarEmoji: '🌹',
  },
  {
    id: 'ai_9',
    name: 'Ravi Patel',
    nickname: 'Thunder Fist',
    record: { wins: 18, losses: 22, draws: 4 },
    reputation: 1800,
    level: 18,
    league: getLeagueFromReputation(1800),
    avatarEmoji: '⚡',
  },
  {
    id: 'ai_10',
    name: 'Olaf Erikson',
    nickname: 'The Viking',
    record: { wins: 16, losses: 25, draws: 3 },
    reputation: 1600,
    level: 16,
    league: getLeagueFromReputation(1600),
    avatarEmoji: '⛵',
  },
  {
    id: 'ai_11',
    name: 'Mei Liu',
    nickname: 'Emerald Fist',
    record: { wins: 14, losses: 28, draws: 2 },
    reputation: 1400,
    level: 14,
    league: getLeagueFromReputation(1400),
    avatarEmoji: '💚',
  },
  {
    id: 'ai_12',
    name: 'James Mitchell',
    nickname: 'Hammer',
    record: { wins: 12, losses: 30, draws: 3 },
    reputation: 1200,
    level: 12,
    league: getLeagueFromReputation(1200),
    avatarEmoji: '🔨',
  },
  {
    id: 'ai_13',
    name: 'Ana Silva',
    nickname: 'Shadow Dancer',
    record: { wins: 10, losses: 32, draws: 2 },
    reputation: 1000,
    level: 10,
    league: getLeagueFromReputation(1000),
    avatarEmoji: '🕺',
  },
  {
    id: 'ai_14',
    name: 'Chen Wei',
    nickname: 'Rising Star',
    record: { wins: 8, losses: 34, draws: 2 },
    reputation: 800,
    level: 8,
    league: getLeagueFromReputation(800),
    avatarEmoji: '⭐',
  },
  {
    id: 'ai_15',
    name: 'Tommy Brown',
    nickname: 'Rookie',
    record: { wins: 3, losses: 37, draws: 1 },
    reputation: 300,
    level: 3,
    league: getLeagueFromReputation(300),
    avatarEmoji: '🥊',
  },
];

export const getLeaderboardRank = (position: number): string => {
  if (position === 1) return '🥇';
  if (position === 2) return '🥈';
  if (position === 3) return '🥉';
  return `#${position}`;
};
